global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s
scrape_configs:
  - job_name: customer-service
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /customer/api/v1/monitor/prometheus
    scheme: http
    follow_redirects: true
    static_configs:
      - targets: ['host.docker.internal:8080']